--- 
config: 
  name: cjdname
foo: bar
fortune: 
  messages: 
    - "People are willing drive far for ice cream."
    - "You learn from your mistakes... You will learn a lot today."
hello: world

workshop: 
  contentURL: "https://workshop-content.cfapps.io"
  title: "Pivotal Cloud Foundry Workshop"
  date: ""
  description: "This workshop will cover the ..."
  customerLogo: ""
  instructors: 
    - 
      name: "Chris Decelles"
      title: "Sr. Platform Architect"
      email: cdecelles@pivotal.io
      phone: "603.512.5616"
  resources:
    -
      title: "Pivotal Network"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "cf CLI Documentation"
      url: "https://docs.pivotal.io/pivotalcf/cf-cli/getting-started.html"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Spring Documentation"
      url: "https://spring.io/docs"
    -
      title: "Spring Initializr"
      url: "http://start.spring.io/"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
  requirements:
    -
      title: "Test"
      requirement:
        -
          content: "content 1 link"
        -
          content: "content 2 link"
    -
      title: "CLI"
      requirement:
      -
        content: "content 3 link"
      -
        content: "content 4 link"
  sessions:
    - 
      id: "agenda"
      name: "Agenda"
      description: "March 6 - 9:00AM - 5:00PM"
      topics:
      -
        id: "session1"
        title: "Application Development"
      -
        id: "04-cli"
      -
        id: "08-deploy-simple-app"
      -
        id: "06-org-space-user-role"
      -
        id: "10-application-manifest"
      -
        id: "12-domains-and-routes"
      -
        id: "lunch"
        title: "Lunch"
      -
        id: "20a-opsmgr-and-bosh-short"
      -
        id: "26-elastic-runtime"
      -
        id: "40-high-availability"
      -
        id: "breakout"
        title: "Afternoon Breakouts"
      -
        id: "bosh"
        title: "Bosh"
      -
        id: "pks"
        title: "PKS"
