--- 
config: 
  name: cjdname
foo: bar
fortune: 
  messages: 
    - "People are willing drive far for ice cream."
    - "You learn from your mistakes... You will learn a lot today."
hello: world

workshop: 
  contentURL: "https://workshop-content.cfapps.io"
  title: "Pivotal Cloud Foundry Workshop"
  date: ""
  description: "This workshop will cover the ..."
  customerLogo: ""
  instructors: 
    - 
      name: "Chris Decelles"
      title: "Sr. Platform Architect"
      email: cdecelles@pivotal.io
      phone: "603.512.5616"
  resources:
    -
      title: "Pivotal Network 0cjd"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "BOSH"
      url: "http://bosh.io/"
    -
      title: "cf CLI Documentation"
      url: "https://docs.pivotal.io/pivotalcf/cf-cli/getting-started.html"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
  sessions:
    - 
      id: "agenda"
      name: "Pre-Event Training"
      description: "March 6 - 9:00AM - 5:00PM"
      topics:
      -
        id: "intro"
        title: "Introductions"
      -
        id: "pd-cf"
      -
        id: "pd-cfa"
      -
        id: "pd-services"
      -
        id: "pd-osbapi"
      -
        id: "lunch"
        title: "Lunch"
      -
        id: "breakout"
        title: "Afternoon Breakouts - Pick 1 (BOSH or PKS)"
      -
        id: "pd-bosh"
      -
        id: "pksheading"
        title: "PKS Topics"
      -
        id: "pd-what-is-pks"
      -
        id: "pd-setup-pks-cluster"
      -
        id: "pd-kubernetes"
      -
        id: "pd-pks-app-deploy"
      -
        id: "pd-helm"
      -
        id: "pd-kibosh"
      -
        id: "retro"
        title: "Retro"
    - 
      id: "day1"
      name: "Day 1"
      description: "Agenda for Day 1"
      topics:
      -
        id: "breakfast2"
        title: "9:00-9:15 AM"
        description: "Breakfast"
      -
        id: "day1talk"
        title: "9:15-10:15 AM"
        description: "Opening talk"
      -
        id: "day1codingam"
        title: "10:15 AM-12:30 PM"
        description: "Coding"
      -
        id: "day1lunch"
        title: "12:30-1:00 PM"
        description: "Lunch"
      -
        id: "day1codingpm"
        title: "1:00-5:00 PM "
        description: "Coding"
    - 
      id: "day2"
      name: "Day 2"
      description: "Agenda Day 2"
      topics:
      -
        id: "breakfast2"
        title: "9:00-9:15 AM"
        description: "Breakfast"
      -
        id: "day2codingam"
        title: "9:15 AM-12:00 PM"
        description: "Coding"
      -
        id: "day2lunch"
        title: "12:00-12:30 PM"
        description: "Lunch"
      -
        id: "day2codingpm"
        title: "12:30-3:30 PM"
        description: "Coding"
      -
        id: "day2demo"
        title: "3:30-5:00 PM"
        description: "Demo presentations"
      -
        id: "day2mixer"
        title: "5:00-6:30 PM"
        description: "Social mixer"
