--- 
config: 
  name: cjdname
foo: bar
fortune: 
  messages: 
    - "People are willing drive far for ice cream."
    - "You learn from your mistakes... You will learn a lot today."
hello: world

workshop: 
  contentURL: "https://pd-content.cfapps.io"
  title: "Pivotal Cloud Foundry Workshop"
  date: "September 11-13, 2018"
  description: "This workshop will cover the ..."
  customerLogo: ""
  instructors: 
    - 
      name: "Chris Decelles"
      title: "Sr. Platform Architect"
      email: cdecelles@pivotal.io
      phone: "603.512.5616"
  resources:
    -
      title: "Pivotal Network"
      url: "https://network.pivotal.io/"
    -
      title: "Pivotal Documentation"
      url: "http://docs.pivotal.io/"
    -
      title: "BOSH"
      url: "http://bosh.io/"
    -
      title: "cf CLI Documentation"
      url: "https://docs.pivotal.io/pivotalcf/cf-cli/getting-started.html"
    -
      title: "Manifest Documentation"
      url: "https://docs.pivotal.io/pivotalcf/devguide/deploy-apps/manifest.html"
    -
      title: "Pivotal Web Services"
      url: "https://run.pivotal.io/"
  sessions:
    - 
      id: "agenda"
      name: "Pre-Event Training"
      description: "September 11 - 8:30AM - 5:00PM"
      topics:
      -
        id: "intro"
        title: "8:30-10:30 AM"
        description: "PCF Overview and Architecture, Lab"
      -
        id: "pd-cf"
      -
        id: "pd-cfa"
      -
        id: "morning-break"
        title: "10:30-10:45 AM - Break"
      -
        id: "intro-s"
        title: "10:45 AM-12:00 PM"
      -
        id: "pd-services"
      -
        id: "pd-osbapi"
      -
        id: "lunch"
        title: "12:00-1:00 PM - Lunch"
      -
        id: "breakout"
        title: "1:00-4:30 PM"
        description: "Afternoon Breakouts - Pick 1 (BOSH or PKS)"
      -
        id: "pd-bosh"
      -
        id: "pksheading"
        title: "PKS Topics"
      -
        id: "pd-pks"
      -
        id: "pd-pks-k8s-lab"
      -
        id: "pd-pks-helm-lab"
      -
        id: "pd-pks-kibosh-lab"
      -
        id: "retro"
        title: "Retro"
    - 
      id: "day1"
      name: "Day One"
      description: "Agenda for Day One - September 12, 1018"
      topics:
      -
        id: "breakfast2"
        title: "8:00-8:30 AM"
        description: "Breakfast"
      -
        id: "day1talk"
        title: "8:30-9:30 AM"
      -
        id: "pd-building-tiles"
      -
        id: "day1codingam"
        title: "9:30 AM-12:00 PM"
        description: "Coding"
      -
        id: "day1lunch"
        title: "12:00-12:30 PM"
        description: "Lunch"
      -
        id: "day1codingpm"
        title: "12:30-5:00 PM "
        description: "Coding"
    - 
      id: "day2"
      name: "Day Two"
      description: "Agenda for Day Two - September 13, 2018"
      topics:
      -
        id: "breakfast2"
        title: "8:00-8:30 AM"
        description: "Breakfast"
      -
        id: "day2codingam"
        title: "8:30 AM-12:00 PM"
        description: "Coding"
      -
        id: "day2lunch"
        title: "12:00-12:30 PM"
        description: "Lunch"
      -
        id: "day2codingpm"
        title: "12:30-3:00 PM"
        description: "Coding"
      -
        id: "day2demo"
        title: "3:00-5:00 PM"
        description: "Demo presentations"
      -
        id: "day2mixer"
        title: "5:00-6:00 PM"
        description: "Social mixer"
